/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_dhashbord (void);
GtkWidget* create_gestion_yassine (void);
GtkWidget* create_ajout_yassine (void);
GtkWidget* create_modifier_yassine (void);
GtkWidget* create_supprimer_yassine (void);
