/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_dhashbord (void)
{
  GtkWidget *dhashbord;
  GtkWidget *fixed3;
  GtkWidget *Quitter;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image7;
  GtkWidget *label9;
  GtkWidget *retour;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image8;
  GtkWidget *label10;
  GtkWidget *button8;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *label8;

  dhashbord = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (dhashbord), _("dhashbord"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (dhashbord), fixed3);

  Quitter = gtk_button_new ();
  gtk_widget_show (Quitter);
  gtk_fixed_put (GTK_FIXED (fixed3), Quitter, 568, 0);
  gtk_widget_set_size_request (Quitter, 112, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (Quitter), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image7 = gtk_image_new_from_stock ("gtk-disconnect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox9), image7, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\" ><b>Quitter</b></span>"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox9), label9, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  retour = gtk_button_new ();
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed3), retour, 0, 0);
  gtk_widget_set_size_request (retour, 96, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (retour), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox10), image8, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\" ><b>Retour</b></span>"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox10), label10, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed3), button8, 144, 64);
  gtk_widget_set_size_request (button8, 392, 160);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button8), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  label8 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>Gestion utilisateur</b></span>"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox8), label8, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  g_signal_connect ((gpointer) Quitter, "clicked",
                    G_CALLBACK (on_MYquitterds_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_gestion_user_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dhashbord, dhashbord, "dhashbord");
  GLADE_HOOKUP_OBJECT (dhashbord, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (dhashbord, Quitter, "Quitter");
  GLADE_HOOKUP_OBJECT (dhashbord, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (dhashbord, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (dhashbord, image7, "image7");
  GLADE_HOOKUP_OBJECT (dhashbord, label9, "label9");
  GLADE_HOOKUP_OBJECT (dhashbord, retour, "retour");
  GLADE_HOOKUP_OBJECT (dhashbord, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (dhashbord, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (dhashbord, image8, "image8");
  GLADE_HOOKUP_OBJECT (dhashbord, label10, "label10");
  GLADE_HOOKUP_OBJECT (dhashbord, button8, "button8");
  GLADE_HOOKUP_OBJECT (dhashbord, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (dhashbord, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (dhashbord, label8, "label8");

  return dhashbord;
}

GtkWidget*
create_gestion_yassine (void)
{
  GtkWidget *gestion_yassine;
  GtkWidget *fixed4;
  GtkWidget *entry_recherche_b;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview_yassine;
  GtkWidget *label12;
  GtkWidget *recherche_yassine;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image12;
  GtkWidget *label16;
  GtkWidget *ajouter_yassine;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image15;
  GtkWidget *label19;
  GtkWidget *supprime_yassine;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image11;
  GtkWidget *label15;
  GtkWidget *modifie_yassine;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image10;
  GtkWidget *label14;
  GtkWidget *afficher_yassine;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image9;
  GtkWidget *label13;
  GtkWidget *label11;
  GtkWidget *button13;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image13;
  GtkWidget *label17;
  GtkWidget *retour_yassine;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image14;
  GtkWidget *label18;

  gestion_yassine = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gestion_yassine, 969, -1);
  gtk_window_set_title (GTK_WINDOW (gestion_yassine), _("Gestion user"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (gestion_yassine), fixed4);

  entry_recherche_b = gtk_entry_new ();
  gtk_widget_show (entry_recherche_b);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_recherche_b, 424, 520);
  gtk_widget_set_size_request (entry_recherche_b, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_recherche_b), 8226);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow1, 48, 88);
  gtk_widget_set_size_request (scrolledwindow1, 848, 320);

  treeview_yassine = gtk_tree_view_new ();
  gtk_widget_show (treeview_yassine);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview_yassine);
  gtk_widget_set_size_request (treeview_yassine, 848, 320);

  label12 = gtk_label_new ("");
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed4), label12, 616, 520);
  gtk_widget_set_size_request (label12, 256, 24);

  recherche_yassine = gtk_button_new ();
  gtk_widget_show (recherche_yassine);
  gtk_fixed_put (GTK_FIXED (fixed4), recherche_yassine, 256, 504);
  gtk_widget_set_size_request (recherche_yassine, 150, 50);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (recherche_yassine), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image12 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox14), image12, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("<span foreground=\"blue\" ><b>Recherche</b></span>"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox14), label16, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  ajouter_yassine = gtk_button_new ();
  gtk_widget_show (ajouter_yassine);
  gtk_fixed_put (GTK_FIXED (fixed4), ajouter_yassine, 648, 424);
  gtk_widget_set_size_request (ajouter_yassine, 150, 50);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (ajouter_yassine), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image15 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox17), image15, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\" ><b>Ajouter</b></span>"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox17), label19, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  supprime_yassine = gtk_button_new ();
  gtk_widget_show (supprime_yassine);
  gtk_fixed_put (GTK_FIXED (fixed4), supprime_yassine, 464, 424);
  gtk_widget_set_size_request (supprime_yassine, 150, 50);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (supprime_yassine), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image11 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox13), image11, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\" ><b>Supprimer</b></span>"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox13), label15, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  modifie_yassine = gtk_button_new ();
  gtk_widget_show (modifie_yassine);
  gtk_fixed_put (GTK_FIXED (fixed4), modifie_yassine, 272, 424);
  gtk_widget_set_size_request (modifie_yassine, 150, 50);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (modifie_yassine), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image10 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox12), image10, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("<span foreground=\"blue\" ><b>Modifier</b></span>"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox12), label14, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  afficher_yassine = gtk_button_new ();
  gtk_widget_show (afficher_yassine);
  gtk_fixed_put (GTK_FIXED (fixed4), afficher_yassine, 96, 424);
  gtk_widget_set_size_request (afficher_yassine, 150, 50);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (afficher_yassine), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image9 = gtk_image_new_from_stock ("gtk-orientation-portrait", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox11), image9, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("<span foreground=\"blue\" ><b>Afficher</b></span>"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox11), label13, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  label11 = gtk_label_new (_("<span foreground=\"black\" ><b>Gestion utilisateur</b></span>"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed4), label11, 288, 16);
  gtk_widget_set_size_request (label11, 400, 40);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed4), button13, 856, 8);
  gtk_widget_set_size_request (button13, 104, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button13), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image13 = gtk_image_new_from_stock ("gtk-disconnect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox15), image13, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\" ><b>Quitter</b></span>"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox15), label17, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  retour_yassine = gtk_button_new ();
  gtk_widget_show (retour_yassine);
  gtk_fixed_put (GTK_FIXED (fixed4), retour_yassine, 16, 0);
  gtk_widget_set_size_request (retour_yassine, 104, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (retour_yassine), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image14 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox16), image14, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\" ><b>Retour</b></span>"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox16), label18, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  g_signal_connect ((gpointer) treeview_yassine, "row_activated",
                    G_CALLBACK (on_treeview_yassine_row_activated),
                    NULL);
  g_signal_connect ((gpointer) recherche_yassine, "clicked",
                    G_CALLBACK (on_recherche_yassine_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_yassine, "clicked",
                    G_CALLBACK (on_ajouter_yassine_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprime_yassine, "clicked",
                    G_CALLBACK (on_supprime_yassine_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifie_yassine, "clicked",
                    G_CALLBACK (on_modifie_yassine_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher_yassine, "clicked",
                    G_CALLBACK (on_afficher_yassine_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_quitter_yassine_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_yassine, "clicked",
                    G_CALLBACK (on_retour_yassine_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_yassine, gestion_yassine, "gestion_yassine");
  GLADE_HOOKUP_OBJECT (gestion_yassine, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gestion_yassine, entry_recherche_b, "entry_recherche_b");
  GLADE_HOOKUP_OBJECT (gestion_yassine, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestion_yassine, treeview_yassine, "treeview_yassine");
  GLADE_HOOKUP_OBJECT (gestion_yassine, label12, "label12");
  GLADE_HOOKUP_OBJECT (gestion_yassine, recherche_yassine, "recherche_yassine");
  GLADE_HOOKUP_OBJECT (gestion_yassine, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (gestion_yassine, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (gestion_yassine, image12, "image12");
  GLADE_HOOKUP_OBJECT (gestion_yassine, label16, "label16");
  GLADE_HOOKUP_OBJECT (gestion_yassine, ajouter_yassine, "ajouter_yassine");
  GLADE_HOOKUP_OBJECT (gestion_yassine, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (gestion_yassine, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (gestion_yassine, image15, "image15");
  GLADE_HOOKUP_OBJECT (gestion_yassine, label19, "label19");
  GLADE_HOOKUP_OBJECT (gestion_yassine, supprime_yassine, "supprime_yassine");
  GLADE_HOOKUP_OBJECT (gestion_yassine, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (gestion_yassine, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (gestion_yassine, image11, "image11");
  GLADE_HOOKUP_OBJECT (gestion_yassine, label15, "label15");
  GLADE_HOOKUP_OBJECT (gestion_yassine, modifie_yassine, "modifie_yassine");
  GLADE_HOOKUP_OBJECT (gestion_yassine, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (gestion_yassine, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (gestion_yassine, image10, "image10");
  GLADE_HOOKUP_OBJECT (gestion_yassine, label14, "label14");
  GLADE_HOOKUP_OBJECT (gestion_yassine, afficher_yassine, "afficher_yassine");
  GLADE_HOOKUP_OBJECT (gestion_yassine, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (gestion_yassine, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (gestion_yassine, image9, "image9");
  GLADE_HOOKUP_OBJECT (gestion_yassine, label13, "label13");
  GLADE_HOOKUP_OBJECT (gestion_yassine, label11, "label11");
  GLADE_HOOKUP_OBJECT (gestion_yassine, button13, "button13");
  GLADE_HOOKUP_OBJECT (gestion_yassine, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (gestion_yassine, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (gestion_yassine, image13, "image13");
  GLADE_HOOKUP_OBJECT (gestion_yassine, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion_yassine, retour_yassine, "retour_yassine");
  GLADE_HOOKUP_OBJECT (gestion_yassine, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (gestion_yassine, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (gestion_yassine, image14, "image14");
  GLADE_HOOKUP_OBJECT (gestion_yassine, label18, "label18");

  return gestion_yassine;
}

GtkWidget*
create_ajout_yassine (void)
{
  GtkWidget *ajout_yassine;
  GtkWidget *fixed5;
  GtkWidget *ya_cin;
  GtkWidget *ya_telephone;
  GtkWidget *ya_nom;
  GtkWidget *ya_prenom;
  GtkObject *spinbutton1_ya_adj;
  GtkWidget *spinbutton1_ya;
  GtkObject *spinbutton2_ya_adj;
  GtkWidget *spinbutton2_ya;
  GtkWidget *ya_nbvote;
  GtkWidget *label21;
  GtkWidget *eventbox1;
  GtkWidget *image16;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *combobox2_ya;
  GtkWidget *radiobutton1_yas;
  GSList *radiobutton1_yas_group = NULL;
  GtkWidget *radiobutton2_yas;
  GtkWidget *annuler_yassine;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image17;
  GtkWidget *label29;
  GtkWidget *confirmer_yassine;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image18;
  GtkWidget *label30;
  GtkWidget *combobox1_ya;
  GtkWidget *label20;

  ajout_yassine = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajout_yassine, 893, 562);
  gtk_window_set_title (GTK_WINDOW (ajout_yassine), _("Formulaire d'ajout"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (ajout_yassine), fixed5);

  ya_cin = gtk_entry_new ();
  gtk_widget_show (ya_cin);
  gtk_fixed_put (GTK_FIXED (fixed5), ya_cin, 424, 56);
  gtk_widget_set_size_request (ya_cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ya_cin), 8226);

  ya_telephone = gtk_entry_new ();
  gtk_widget_show (ya_telephone);
  gtk_fixed_put (GTK_FIXED (fixed5), ya_telephone, 424, 128);
  gtk_widget_set_size_request (ya_telephone, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ya_telephone), 8226);

  ya_nom = gtk_entry_new ();
  gtk_widget_show (ya_nom);
  gtk_fixed_put (GTK_FIXED (fixed5), ya_nom, 424, 184);
  gtk_widget_set_size_request (ya_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ya_nom), 8226);

  ya_prenom = gtk_entry_new ();
  gtk_widget_show (ya_prenom);
  gtk_fixed_put (GTK_FIXED (fixed5), ya_prenom, 424, 232);
  gtk_widget_set_size_request (ya_prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ya_prenom), 8226);

  spinbutton1_ya_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1_ya = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_ya_adj), 1, 0);
  gtk_widget_show (spinbutton1_ya);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton1_ya, 432, 280);
  gtk_widget_set_size_request (spinbutton1_ya, 60, 27);

  spinbutton2_ya_adj = gtk_adjustment_new (1, 1930, 2005, 1, 10, 10);
  spinbutton2_ya = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_ya_adj), 1, 0);
  gtk_widget_show (spinbutton2_ya);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton2_ya, 624, 280);
  gtk_widget_set_size_request (spinbutton2_ya, 60, 27);

  ya_nbvote = gtk_entry_new ();
  gtk_widget_show (ya_nbvote);
  gtk_fixed_put (GTK_FIXED (fixed5), ya_nbvote, 448, 480);
  gtk_widget_set_size_request (ya_nbvote, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ya_nbvote), 8226);

  label21 = gtk_label_new (_("<span foreground=\"black\" ><b>CIN</b></span>"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed5), label21, 280, 56);
  gtk_widget_set_size_request (label21, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_fixed_put (GTK_FIXED (fixed5), eventbox1, 8, 32);
  gtk_widget_set_size_request (eventbox1, 288, 320);

  image16 = create_pixmap (ajout_yassine, "1122.png");
  gtk_widget_show (image16);
  gtk_container_add (GTK_CONTAINER (eventbox1), image16);
  gtk_widget_set_size_request (image16, 288, 320);

  label22 = gtk_label_new (_("<span foreground=\"black\" ><b>N\302\260telephone</b></span>"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed5), label22, 280, 128);
  gtk_widget_set_size_request (label22, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  label23 = gtk_label_new (_("<span foreground=\"black\" ><b>Nom</b></span>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed5), label23, 280, 184);
  gtk_widget_set_size_request (label23, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  label24 = gtk_label_new (_("<span foreground=\"black\" ><b>Prenom</b></span>"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed5), label24, 280, 232);
  gtk_widget_set_size_request (label24, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  label25 = gtk_label_new (_("<span foreground=\"black\" ><b>Date de naissance</b></span>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed5), label25, 272, 280);
  gtk_widget_set_size_request (label25, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  label26 = gtk_label_new (_("<span foreground=\"black\" ><b>Role</b></span>"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed5), label26, 280, 352);
  gtk_widget_set_size_request (label26, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  label27 = gtk_label_new (_("<span foreground=\"black\" ><b>Genre</b></span>"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed5), label27, 280, 408);
  gtk_widget_set_size_request (label27, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  label28 = gtk_label_new (_("<span foreground=\"black\" ><b>NB vote</b></span>"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed5), label28, 272, 480);
  gtk_widget_set_size_request (label28, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  combobox2_ya = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2_ya);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox2_ya, 440, 344);
  gtk_widget_set_size_request (combobox2_ya, 160, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2_ya), _("Electeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2_ya), _("Agent"));

  radiobutton1_yas = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton1_yas);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton1_yas, 432, 416);
  gtk_widget_set_size_request (radiobutton1_yas, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_yas), radiobutton1_yas_group);
  radiobutton1_yas_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_yas));

  radiobutton2_yas = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton2_yas);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton2_yas, 584, 416);
  gtk_widget_set_size_request (radiobutton2_yas, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2_yas), radiobutton1_yas_group);
  radiobutton1_yas_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2_yas));

  annuler_yassine = gtk_button_new ();
  gtk_widget_show (annuler_yassine);
  gtk_fixed_put (GTK_FIXED (fixed5), annuler_yassine, 200, 568);
  gtk_widget_set_size_request (annuler_yassine, 150, 34);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (annuler_yassine), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image17 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox18), image17, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\" ><b>Annuler</b></span>"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox18), label29, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  confirmer_yassine = gtk_button_new ();
  gtk_widget_show (confirmer_yassine);
  gtk_fixed_put (GTK_FIXED (fixed5), confirmer_yassine, 408, 568);
  gtk_widget_set_size_request (confirmer_yassine, 150, 34);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (confirmer_yassine), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image18 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox19), image18, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\" ><b>Confirmer</b></span>"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox19), label30, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  combobox1_ya = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1_ya);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox1_ya, 504, 280);
  gtk_widget_set_size_request (combobox1_ya, 104, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_ya), _("Janvier "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_ya), _("Fevrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_ya), _("Mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_ya), _("Avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_ya), _("May "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_ya), _("Juin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_ya), _("Juillet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_ya), _("Aout"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_ya), _("Septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_ya), _("Octobre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_ya), _("Novembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_ya), _("Decembre"));

  label20 = gtk_label_new (_("<span foreground=\"black\" ><b>Ajouter utilisateur</b></span>"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed5), label20, 168, 8);
  gtk_widget_set_size_request (label20, 400, 40);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  g_signal_connect ((gpointer) radiobutton1_yas, "toggled",
                    G_CALLBACK (on_radiobutton1_yas_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2_yas, "toggled",
                    G_CALLBACK (on_radiobutton2_yas_toggled),
                    NULL);
  g_signal_connect ((gpointer) annuler_yassine, "clicked",
                    G_CALLBACK (on_annuler_yassine_clicked),
                    NULL);
  g_signal_connect ((gpointer) confirmer_yassine, "clicked",
                    G_CALLBACK (on_confirmer_yassine_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_yassine, ajout_yassine, "ajout_yassine");
  GLADE_HOOKUP_OBJECT (ajout_yassine, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (ajout_yassine, ya_cin, "ya_cin");
  GLADE_HOOKUP_OBJECT (ajout_yassine, ya_telephone, "ya_telephone");
  GLADE_HOOKUP_OBJECT (ajout_yassine, ya_nom, "ya_nom");
  GLADE_HOOKUP_OBJECT (ajout_yassine, ya_prenom, "ya_prenom");
  GLADE_HOOKUP_OBJECT (ajout_yassine, spinbutton1_ya, "spinbutton1_ya");
  GLADE_HOOKUP_OBJECT (ajout_yassine, spinbutton2_ya, "spinbutton2_ya");
  GLADE_HOOKUP_OBJECT (ajout_yassine, ya_nbvote, "ya_nbvote");
  GLADE_HOOKUP_OBJECT (ajout_yassine, label21, "label21");
  GLADE_HOOKUP_OBJECT (ajout_yassine, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (ajout_yassine, image16, "image16");
  GLADE_HOOKUP_OBJECT (ajout_yassine, label22, "label22");
  GLADE_HOOKUP_OBJECT (ajout_yassine, label23, "label23");
  GLADE_HOOKUP_OBJECT (ajout_yassine, label24, "label24");
  GLADE_HOOKUP_OBJECT (ajout_yassine, label25, "label25");
  GLADE_HOOKUP_OBJECT (ajout_yassine, label26, "label26");
  GLADE_HOOKUP_OBJECT (ajout_yassine, label27, "label27");
  GLADE_HOOKUP_OBJECT (ajout_yassine, label28, "label28");
  GLADE_HOOKUP_OBJECT (ajout_yassine, combobox2_ya, "combobox2_ya");
  GLADE_HOOKUP_OBJECT (ajout_yassine, radiobutton1_yas, "radiobutton1_yas");
  GLADE_HOOKUP_OBJECT (ajout_yassine, radiobutton2_yas, "radiobutton2_yas");
  GLADE_HOOKUP_OBJECT (ajout_yassine, annuler_yassine, "annuler_yassine");
  GLADE_HOOKUP_OBJECT (ajout_yassine, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (ajout_yassine, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (ajout_yassine, image17, "image17");
  GLADE_HOOKUP_OBJECT (ajout_yassine, label29, "label29");
  GLADE_HOOKUP_OBJECT (ajout_yassine, confirmer_yassine, "confirmer_yassine");
  GLADE_HOOKUP_OBJECT (ajout_yassine, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (ajout_yassine, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (ajout_yassine, image18, "image18");
  GLADE_HOOKUP_OBJECT (ajout_yassine, label30, "label30");
  GLADE_HOOKUP_OBJECT (ajout_yassine, combobox1_ya, "combobox1_ya");
  GLADE_HOOKUP_OBJECT (ajout_yassine, label20, "label20");

  return ajout_yassine;
}

GtkWidget*
create_modifier_yassine (void)
{
  GtkWidget *modifier_yassine;
  GtkWidget *fixed6;
  GtkWidget *y_cin;
  GtkWidget *label31;
  GtkWidget *y_telephone;
  GtkWidget *y_nom;
  GtkWidget *y_prenom;
  GtkObject *spinbutton12_y_adj;
  GtkWidget *spinbutton12_y;
  GtkObject *spinbutton2_y_adj;
  GtkWidget *spinbutton2_y;
  GtkWidget *y_nbvote;
  GtkWidget *eventbox2;
  GtkWidget *image19;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *combobox13_y;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *enregistrer_yassine;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label41;
  GtkWidget *annuler_yassine;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label40;
  GtkWidget *combobox12_y;
  GtkWidget *label32;

  modifier_yassine = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_yassine), _("Modfier"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (modifier_yassine), fixed6);
  gtk_widget_set_size_request (fixed6, 917, 518);

  y_cin = gtk_entry_new ();
  gtk_widget_show (y_cin);
  gtk_fixed_put (GTK_FIXED (fixed6), y_cin, 448, 64);
  gtk_widget_set_size_request (y_cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (y_cin), 8226);

  label31 = gtk_label_new (_("<span foreground=\"black\" ><b>CIN</b></span>"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed6), label31, 304, 64);
  gtk_widget_set_size_request (label31, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  y_telephone = gtk_entry_new ();
  gtk_widget_show (y_telephone);
  gtk_fixed_put (GTK_FIXED (fixed6), y_telephone, 448, 120);
  gtk_widget_set_size_request (y_telephone, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (y_telephone), 8226);

  y_nom = gtk_entry_new ();
  gtk_widget_show (y_nom);
  gtk_fixed_put (GTK_FIXED (fixed6), y_nom, 448, 168);
  gtk_widget_set_size_request (y_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (y_nom), 8226);

  y_prenom = gtk_entry_new ();
  gtk_widget_show (y_prenom);
  gtk_fixed_put (GTK_FIXED (fixed6), y_prenom, 448, 224);
  gtk_widget_set_size_request (y_prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (y_prenom), 8226);

  spinbutton12_y_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton12_y = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton12_y_adj), 1, 0);
  gtk_widget_show (spinbutton12_y);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton12_y, 448, 272);
  gtk_widget_set_size_request (spinbutton12_y, 60, 27);

  spinbutton2_y_adj = gtk_adjustment_new (1, 1930, 2005, 1, 10, 10);
  spinbutton2_y = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_y_adj), 1, 0);
  gtk_widget_show (spinbutton2_y);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton2_y, 672, 272);
  gtk_widget_set_size_request (spinbutton2_y, 60, 27);

  y_nbvote = gtk_entry_new ();
  gtk_widget_show (y_nbvote);
  gtk_fixed_put (GTK_FIXED (fixed6), y_nbvote, 472, 456);
  gtk_widget_set_size_request (y_nbvote, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (y_nbvote), 8226);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox2, 0, 8);
  gtk_widget_set_size_request (eventbox2, 312, 360);

  image19 = create_pixmap (modifier_yassine, "images.jpeg");
  gtk_widget_show (image19);
  gtk_container_add (GTK_CONTAINER (eventbox2), image19);
  gtk_widget_set_size_request (image19, 312, 360);

  label33 = gtk_label_new (_("<span foreground=\"black\" ><b>N\302\260telephone</b></span>"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed6), label33, 304, 120);
  gtk_widget_set_size_request (label33, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  label34 = gtk_label_new (_("<span foreground=\"black\" ><b>Nom</b></span>"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed6), label34, 288, 168);
  gtk_widget_set_size_request (label34, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  label35 = gtk_label_new (_("<span foreground=\"black\" ><b>Prenom</b></span>"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed6), label35, 288, 224);
  gtk_widget_set_size_request (label35, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);

  label36 = gtk_label_new (_("<span foreground=\"black\" ><b>Date de naissance</b></span>"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed6), label36, 280, 272);
  gtk_widget_set_size_request (label36, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  label37 = gtk_label_new (_("<span foreground=\"black\" ><b>Role</b></span>"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed6), label37, 288, 336);
  gtk_widget_set_size_request (label37, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  label38 = gtk_label_new (_("<span foreground=\"black\" ><b>Genre</b></span>"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed6), label38, 288, 384);
  gtk_widget_set_size_request (label38, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  label39 = gtk_label_new (_("<span foreground=\"black\" ><b>NB vote</b></span>"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed6), label39, 288, 448);
  gtk_widget_set_size_request (label39, 150, 27);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  combobox13_y = gtk_combo_box_new_text ();
  gtk_widget_show (combobox13_y);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox13_y, 464, 328);
  gtk_widget_set_size_request (combobox13_y, 160, 27);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13_y), _("Electeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13_y), _("Agent"));

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobutton1, 448, 384);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobutton2, 592, 384);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  enregistrer_yassine = gtk_button_new ();
  gtk_widget_show (enregistrer_yassine);
  gtk_fixed_put (GTK_FIXED (fixed6), enregistrer_yassine, 432, 512);
  gtk_widget_set_size_request (enregistrer_yassine, 150, 35);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (enregistrer_yassine), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\" ><b>Enregistrer</b></span>"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox21), label41, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  annuler_yassine = gtk_button_new ();
  gtk_widget_show (annuler_yassine);
  gtk_fixed_put (GTK_FIXED (fixed6), annuler_yassine, 224, 512);
  gtk_widget_set_size_request (annuler_yassine, 150, 35);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (annuler_yassine), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\" ><b>Annuler</b></span>"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox20), label40, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  combobox12_y = gtk_combo_box_new_text ();
  gtk_widget_show (combobox12_y);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox12_y, 512, 272);
  gtk_widget_set_size_request (combobox12_y, 130, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12_y), _("Janvier "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12_y), _("Fevrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12_y), _("Mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12_y), _("Avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12_y), _("May "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12_y), _("Juin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12_y), _("Juillet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12_y), _("Aout"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12_y), _("Septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12_y), _("Octobre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12_y), _("Novembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12_y), _("Decembre"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (combobox12_y), TRUE);

  label32 = gtk_label_new (_("<span foreground=\"black\" ><b>Modification d'utilisateur</b></span>"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed6), label32, 336, 8);
  gtk_widget_set_size_request (label32, 400, 40);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton3_y_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton4_y_toggled),
                    NULL);
  g_signal_connect ((gpointer) enregistrer_yassine, "clicked",
                    G_CALLBACK (on_enregistrer_yassine_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler_yassine, "clicked",
                    G_CALLBACK (on_annuler2_yassine_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_yassine, modifier_yassine, "modifier_yassine");
  GLADE_HOOKUP_OBJECT (modifier_yassine, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (modifier_yassine, y_cin, "y_cin");
  GLADE_HOOKUP_OBJECT (modifier_yassine, label31, "label31");
  GLADE_HOOKUP_OBJECT (modifier_yassine, y_telephone, "y_telephone");
  GLADE_HOOKUP_OBJECT (modifier_yassine, y_nom, "y_nom");
  GLADE_HOOKUP_OBJECT (modifier_yassine, y_prenom, "y_prenom");
  GLADE_HOOKUP_OBJECT (modifier_yassine, spinbutton12_y, "spinbutton12_y");
  GLADE_HOOKUP_OBJECT (modifier_yassine, spinbutton2_y, "spinbutton2_y");
  GLADE_HOOKUP_OBJECT (modifier_yassine, y_nbvote, "y_nbvote");
  GLADE_HOOKUP_OBJECT (modifier_yassine, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (modifier_yassine, image19, "image19");
  GLADE_HOOKUP_OBJECT (modifier_yassine, label33, "label33");
  GLADE_HOOKUP_OBJECT (modifier_yassine, label34, "label34");
  GLADE_HOOKUP_OBJECT (modifier_yassine, label35, "label35");
  GLADE_HOOKUP_OBJECT (modifier_yassine, label36, "label36");
  GLADE_HOOKUP_OBJECT (modifier_yassine, label37, "label37");
  GLADE_HOOKUP_OBJECT (modifier_yassine, label38, "label38");
  GLADE_HOOKUP_OBJECT (modifier_yassine, label39, "label39");
  GLADE_HOOKUP_OBJECT (modifier_yassine, combobox13_y, "combobox13_y");
  GLADE_HOOKUP_OBJECT (modifier_yassine, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (modifier_yassine, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (modifier_yassine, enregistrer_yassine, "enregistrer_yassine");
  GLADE_HOOKUP_OBJECT (modifier_yassine, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (modifier_yassine, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (modifier_yassine, image21, "image21");
  GLADE_HOOKUP_OBJECT (modifier_yassine, label41, "label41");
  GLADE_HOOKUP_OBJECT (modifier_yassine, annuler_yassine, "annuler_yassine");
  GLADE_HOOKUP_OBJECT (modifier_yassine, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (modifier_yassine, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (modifier_yassine, image20, "image20");
  GLADE_HOOKUP_OBJECT (modifier_yassine, label40, "label40");
  GLADE_HOOKUP_OBJECT (modifier_yassine, combobox12_y, "combobox12_y");
  GLADE_HOOKUP_OBJECT (modifier_yassine, label32, "label32");

  return modifier_yassine;
}

GtkWidget*
create_supprimer_yassine (void)
{
  GtkWidget *supprimer_yassine;
  GtkWidget *fixed7;
  GtkWidget *eventbox3;
  GtkWidget *image22;
  GtkWidget *entry1;
  GtkWidget *nonb_supprimer;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image23;
  GtkWidget *label44;
  GtkWidget *button15;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image24;
  GtkWidget *label45;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *label46;

  supprimer_yassine = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer_yassine), _("Supprimer"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (supprimer_yassine), fixed7);

  eventbox3 = gtk_event_box_new ();
  gtk_widget_show (eventbox3);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox3, 136, 168);
  gtk_widget_set_size_request (eventbox3, 536, 376);

  image22 = create_pixmap (supprimer_yassine, "6a00d834529bc369e2014e60136a5c970c-800wi.jpg");
  gtk_widget_show (image22);
  gtk_container_add (GTK_CONTAINER (eventbox3), image22);
  gtk_widget_set_size_request (image22, 536, 376);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed7), entry1, 248, 16);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  nonb_supprimer = gtk_button_new ();
  gtk_widget_show (nonb_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed7), nonb_supprimer, 408, 96);
  gtk_widget_set_size_request (nonb_supprimer, 100, 35);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (nonb_supprimer), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image23 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox22), image23, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\" ><b>NON</b></span>"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox22), label44, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed7), button15, 176, 96);
  gtk_widget_set_size_request (button15, 96, 32);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button15), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image24 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox23), image24, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\" ><b>OUI</b></span>"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox23), label45, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label45), TRUE);

  label42 = gtk_label_new (_("<span foreground=\"black\" ><b>CIN :</b></span>"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed7), label42, 24, 8);
  gtk_widget_set_size_request (label42, 192, 40);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  label43 = gtk_label_new ("");
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed7), label43, 456, 16);
  gtk_widget_set_size_request (label43, 208, 48);

  label46 = gtk_label_new (_("<span foreground=\"black\" ><b>Vouler vous supprimer observateur ?</b></span>"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed7), label46, 184, 56);
  gtk_widget_set_size_request (label46, 288, 32);
  gtk_label_set_use_markup (GTK_LABEL (label46), TRUE);

  g_signal_connect ((gpointer) nonb_supprimer, "clicked",
                    G_CALLBACK (on_nonb_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_yassine, supprimer_yassine, "supprimer_yassine");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, eventbox3, "eventbox3");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, image22, "image22");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, nonb_supprimer, "nonb_supprimer");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, image23, "image23");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, label44, "label44");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, button15, "button15");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, image24, "image24");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, label45, "label45");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, label42, "label42");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, label43, "label43");
  GLADE_HOOKUP_OBJECT (supprimer_yassine, label46, "label46");

  return supprimer_yassine;
}

