/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Gestion_observateur (void)
{
  GtkWidget *Gestion_observateur;
  GtkWidget *fixed39;
  GtkWidget *fixed29;
  GtkWidget *treeview7;
  GtkWidget *entre_rech;
  GtkWidget *label332;
  GtkWidget *buttonrechercher_obs;
  GtkWidget *alignment68;
  GtkWidget *hbox67;
  GtkWidget *image66;
  GtkWidget *label330;
  GtkWidget *label333;
  GtkWidget *button_modifier_obs;
  GtkWidget *alignment54;
  GtkWidget *hbox53;
  GtkWidget *image52;
  GtkWidget *label216;
  GtkWidget *button_ajouter_obs;
  GtkWidget *alignment55;
  GtkWidget *hbox54;
  GtkWidget *image53;
  GtkWidget *label217;
  GtkWidget *button_supprimer_obs;
  GtkWidget *alignment53;
  GtkWidget *hbox52;
  GtkWidget *image51;
  GtkWidget *label215;
  GtkWidget *button_afficher_obs;
  GtkWidget *alignment69;
  GtkWidget *hbox68;
  GtkWidget *image67;
  GtkWidget *label331;

  Gestion_observateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_observateur), _("Gestion Observateur"));

  fixed39 = gtk_fixed_new ();
  gtk_widget_show (fixed39);
  gtk_container_add (GTK_CONTAINER (Gestion_observateur), fixed39);

  fixed29 = gtk_fixed_new ();
  gtk_widget_show (fixed29);
  gtk_fixed_put (GTK_FIXED (fixed39), fixed29, 0, 0);
  gtk_widget_set_size_request (fixed29, 920, 654);

  treeview7 = gtk_tree_view_new ();
  gtk_widget_show (treeview7);
  gtk_fixed_put (GTK_FIXED (fixed29), treeview7, 80, 128);
  gtk_widget_set_size_request (treeview7, 776, 248);

  entre_rech = gtk_entry_new ();
  gtk_widget_show (entre_rech);
  gtk_fixed_put (GTK_FIXED (fixed29), entre_rech, 432, 568);
  gtk_widget_set_size_request (entre_rech, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entre_rech), 8226);

  label332 = gtk_label_new (_("Entrer ID :"));
  gtk_widget_show (label332);
  gtk_fixed_put (GTK_FIXED (fixed29), label332, 336, 568);
  gtk_widget_set_size_request (label332, 88, 32);

  buttonrechercher_obs = gtk_button_new ();
  gtk_widget_show (buttonrechercher_obs);
  gtk_fixed_put (GTK_FIXED (fixed29), buttonrechercher_obs, 200, 552);
  gtk_widget_set_size_request (buttonrechercher_obs, 120, 40);

  alignment68 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment68);
  gtk_container_add (GTK_CONTAINER (buttonrechercher_obs), alignment68);

  hbox67 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox67);
  gtk_container_add (GTK_CONTAINER (alignment68), hbox67);

  image66 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image66);
  gtk_box_pack_start (GTK_BOX (hbox67), image66, FALSE, FALSE, 0);

  label330 = gtk_label_new_with_mnemonic (_("<span foreground=\"blue\"><b>Recherche</b></span>"));
  gtk_widget_show (label330);
  gtk_box_pack_start (GTK_BOX (hbox67), label330, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label330), TRUE);

  label333 = gtk_label_new (_("Gestion Observateur"));
  gtk_widget_show (label333);
  gtk_fixed_put (GTK_FIXED (fixed29), label333, 344, 32);
  gtk_widget_set_size_request (label333, 272, 64);

  button_modifier_obs = gtk_button_new ();
  gtk_widget_show (button_modifier_obs);
  gtk_fixed_put (GTK_FIXED (fixed29), button_modifier_obs, 200, 448);
  gtk_widget_set_size_request (button_modifier_obs, 104, 48);

  alignment54 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment54);
  gtk_container_add (GTK_CONTAINER (button_modifier_obs), alignment54);

  hbox53 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox53);
  gtk_container_add (GTK_CONTAINER (alignment54), hbox53);

  image52 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image52);
  gtk_box_pack_start (GTK_BOX (hbox53), image52, FALSE, FALSE, 0);

  label216 = gtk_label_new_with_mnemonic (_("<span foreground=\"blue\"><b>Modifier</b></span>"));
  gtk_widget_show (label216);
  gtk_box_pack_start (GTK_BOX (hbox53), label216, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label216), TRUE);

  button_ajouter_obs = gtk_button_new ();
  gtk_widget_show (button_ajouter_obs);
  gtk_fixed_put (GTK_FIXED (fixed29), button_ajouter_obs, 456, 448);
  gtk_widget_set_size_request (button_ajouter_obs, 112, 48);

  alignment55 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment55);
  gtk_container_add (GTK_CONTAINER (button_ajouter_obs), alignment55);

  hbox54 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox54);
  gtk_container_add (GTK_CONTAINER (alignment55), hbox54);

  image53 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image53);
  gtk_box_pack_start (GTK_BOX (hbox54), image53, FALSE, FALSE, 0);

  label217 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>Ajouter</b></span>"));
  gtk_widget_show (label217);
  gtk_box_pack_start (GTK_BOX (hbox54), label217, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label217), TRUE);

  button_supprimer_obs = gtk_button_new ();
  gtk_widget_show (button_supprimer_obs);
  gtk_fixed_put (GTK_FIXED (fixed29), button_supprimer_obs, 328, 448);
  gtk_widget_set_size_request (button_supprimer_obs, 104, 48);

  alignment53 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment53);
  gtk_container_add (GTK_CONTAINER (button_supprimer_obs), alignment53);

  hbox52 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox52);
  gtk_container_add (GTK_CONTAINER (alignment53), hbox52);

  image51 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image51);
  gtk_box_pack_start (GTK_BOX (hbox52), image51, FALSE, FALSE, 0);

  label215 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Supprimer</b></span>"));
  gtk_widget_show (label215);
  gtk_box_pack_start (GTK_BOX (hbox52), label215, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label215), TRUE);

  button_afficher_obs = gtk_button_new ();
  gtk_widget_show (button_afficher_obs);
  gtk_fixed_put (GTK_FIXED (fixed29), button_afficher_obs, 72, 448);
  gtk_widget_set_size_request (button_afficher_obs, 120, 48);

  alignment69 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment69);
  gtk_container_add (GTK_CONTAINER (button_afficher_obs), alignment69);

  hbox68 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox68);
  gtk_container_add (GTK_CONTAINER (alignment69), hbox68);

  image67 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image67);
  gtk_box_pack_start (GTK_BOX (hbox68), image67, FALSE, FALSE, 0);

  label331 = gtk_label_new_with_mnemonic (_("<span foreground=\"blue\"><b>Afficher</b></span>"));
  gtk_widget_show (label331);
  gtk_box_pack_start (GTK_BOX (hbox68), label331, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label331), TRUE);

  g_signal_connect ((gpointer) treeview7, "row_activated",
                    G_CALLBACK (on_treeview7_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonrechercher_obs, "clicked",
                    G_CALLBACK (on_buttonrechercher_obs_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier_obs, "clicked",
                    G_CALLBACK (on_button_modifier_obs_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter_obs, "clicked",
                    G_CALLBACK (on_button_ajouter_obs_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer_obs, "clicked",
                    G_CALLBACK (on_button_supprimer_obs_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_afficher_obs, "clicked",
                    G_CALLBACK (on_button_afficher_obs_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_observateur, Gestion_observateur, "Gestion_observateur");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, fixed39, "fixed39");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, fixed29, "fixed29");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, treeview7, "treeview7");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, entre_rech, "entre_rech");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, label332, "label332");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, buttonrechercher_obs, "buttonrechercher_obs");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, alignment68, "alignment68");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, hbox67, "hbox67");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, image66, "image66");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, label330, "label330");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, label333, "label333");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, button_modifier_obs, "button_modifier_obs");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, alignment54, "alignment54");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, hbox53, "hbox53");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, image52, "image52");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, label216, "label216");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, button_ajouter_obs, "button_ajouter_obs");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, alignment55, "alignment55");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, hbox54, "hbox54");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, image53, "image53");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, label217, "label217");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, button_supprimer_obs, "button_supprimer_obs");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, alignment53, "alignment53");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, hbox52, "hbox52");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, image51, "image51");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, label215, "label215");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, button_afficher_obs, "button_afficher_obs");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, alignment69, "alignment69");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, hbox68, "hbox68");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, image67, "image67");
  GLADE_HOOKUP_OBJECT (Gestion_observateur, label331, "label331");

  return Gestion_observateur;
}

GtkWidget*
create_Ajouter_observateur (void)
{
  GtkWidget *Ajouter_observateur;
  GtkWidget *fixed40;
  GtkWidget *fixed34;
  GtkWidget *entry_pass;
  GtkWidget *fixed35;
  GtkWidget *entry_nom_obs;
  GtkWidget *entry_prenom_obs;
  GtkObject *spinbutton38_adj;
  GtkWidget *spinbutton38;
  GtkObject *spinbutton39_adj;
  GtkWidget *spinbutton39;
  GtkObject *spinbutton40_adj;
  GtkWidget *spinbutton40;
  GtkWidget *entry_id_obs;
  GtkWidget *comboboxentry19;
  GtkWidget *checkbutton1_ajt_obs;
  GtkWidget *checkbutton4_ajt_obs;
  GtkWidget *checkbutton3_ajt_obs;
  GtkWidget *checkbutton5_ajt_obs;
  GtkWidget *radiobutton44;
  GSList *radiobutton44_group = NULL;
  GtkWidget *radiobutton43;
  GtkWidget *button_retour_ajouter;
  GtkWidget *alignment64;
  GtkWidget *hbox63;
  GtkWidget *image62;
  GtkWidget *label292;
  GtkWidget *button_ok_ajouter_obs;
  GtkWidget *alignment63;
  GtkWidget *hbox62;
  GtkWidget *image61;
  GtkWidget *label289;
  GtkWidget *checkbuttonOrganisationmondial;
  GtkWidget *label284;
  GtkWidget *label334;
  GtkWidget *label283;
  GtkWidget *label281;
  GtkWidget *label277;
  GtkWidget *label278;
  GtkWidget *label279;
  GtkWidget *label274;
  GtkWidget *label280;

  Ajouter_observateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Ajouter_observateur, 630, 550);
  gtk_window_set_title (GTK_WINDOW (Ajouter_observateur), _("Ajouter Observateur"));

  fixed40 = gtk_fixed_new ();
  gtk_widget_show (fixed40);
  gtk_container_add (GTK_CONTAINER (Ajouter_observateur), fixed40);
  gtk_widget_set_size_request (fixed40, 630, 550);

  fixed34 = gtk_fixed_new ();
  gtk_widget_show (fixed34);
  gtk_fixed_put (GTK_FIXED (fixed40), fixed34, 0, 0);
  gtk_widget_set_size_request (fixed34, 0, 0);

  entry_pass = gtk_entry_new ();
  gtk_widget_show (entry_pass);
  gtk_fixed_put (GTK_FIXED (fixed34), entry_pass, 200, 264);
  gtk_widget_set_size_request (entry_pass, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_pass), 8226);

  fixed35 = gtk_fixed_new ();
  gtk_widget_show (fixed35);
  gtk_fixed_put (GTK_FIXED (fixed34), fixed35, 160, 136);
  gtk_widget_set_size_request (fixed35, 50, 50);

  entry_nom_obs = gtk_entry_new ();
  gtk_widget_show (entry_nom_obs);
  gtk_fixed_put (GTK_FIXED (fixed34), entry_nom_obs, 200, 112);
  gtk_widget_set_size_request (entry_nom_obs, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_obs), 8226);

  entry_prenom_obs = gtk_entry_new ();
  gtk_widget_show (entry_prenom_obs);
  gtk_fixed_put (GTK_FIXED (fixed34), entry_prenom_obs, 200, 72);
  gtk_widget_set_size_request (entry_prenom_obs, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom_obs), 8226);

  spinbutton38_adj = gtk_adjustment_new (23, 1, 31, 1, 10, 10);
  spinbutton38 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton38_adj), 1, 0);
  gtk_widget_show (spinbutton38);
  gtk_fixed_put (GTK_FIXED (fixed34), spinbutton38, 192, 144);
  gtk_widget_set_size_request (spinbutton38, 60, 27);

  spinbutton39_adj = gtk_adjustment_new (12, 1, 12, 1, 10, 10);
  spinbutton39 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton39_adj), 1, 0);
  gtk_widget_show (spinbutton39);
  gtk_fixed_put (GTK_FIXED (fixed34), spinbutton39, 256, 144);
  gtk_widget_set_size_request (spinbutton39, 60, 27);

  spinbutton40_adj = gtk_adjustment_new (2000, 1899, 2005, 1, 10, 10);
  spinbutton40 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton40_adj), 1, 0);
  gtk_widget_show (spinbutton40);
  gtk_fixed_put (GTK_FIXED (fixed34), spinbutton40, 320, 144);
  gtk_widget_set_size_request (spinbutton40, 60, 27);

  entry_id_obs = gtk_entry_new ();
  gtk_widget_show (entry_id_obs);
  gtk_fixed_put (GTK_FIXED (fixed34), entry_id_obs, 200, 40);
  gtk_widget_set_size_request (entry_id_obs, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_obs), 8226);

  comboboxentry19 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry19);
  gtk_fixed_put (GTK_FIXED (fixed34), comboboxentry19, 192, 224);
  gtk_widget_set_size_request (comboboxentry19, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry19), _("Nationale"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry19), _("Internationale"));

  checkbutton1_ajt_obs = gtk_check_button_new_with_mnemonic (_("Parti politique"));
  gtk_widget_show (checkbutton1_ajt_obs);
  gtk_fixed_put (GTK_FIXED (fixed34), checkbutton1_ajt_obs, 192, 328);
  gtk_widget_set_size_request (checkbutton1_ajt_obs, 168, 32);

  checkbutton4_ajt_obs = gtk_check_button_new_with_mnemonic (_("Presse "));
  gtk_widget_show (checkbutton4_ajt_obs);
  gtk_fixed_put (GTK_FIXED (fixed34), checkbutton4_ajt_obs, 192, 424);
  gtk_widget_set_size_request (checkbutton4_ajt_obs, 120, 24);

  checkbutton3_ajt_obs = gtk_check_button_new_with_mnemonic (_("Hote"));
  gtk_widget_show (checkbutton3_ajt_obs);
  gtk_fixed_put (GTK_FIXED (fixed34), checkbutton3_ajt_obs, 192, 400);
  gtk_widget_set_size_request (checkbutton3_ajt_obs, 96, 24);

  checkbutton5_ajt_obs = gtk_check_button_new_with_mnemonic (_("Societ\303\251 civile"));
  gtk_widget_show (checkbutton5_ajt_obs);
  gtk_fixed_put (GTK_FIXED (fixed34), checkbutton5_ajt_obs, 192, 456);
  gtk_widget_set_size_request (checkbutton5_ajt_obs, 152, 24);

  radiobutton44 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton44);
  gtk_fixed_put (GTK_FIXED (fixed34), radiobutton44, 280, 184);
  gtk_widget_set_size_request (radiobutton44, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton44), radiobutton44_group);
  radiobutton44_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton44));

  radiobutton43 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton43);
  gtk_fixed_put (GTK_FIXED (fixed34), radiobutton43, 184, 184);
  gtk_widget_set_size_request (radiobutton43, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton43), radiobutton44_group);
  radiobutton44_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton43));

  button_retour_ajouter = gtk_button_new ();
  gtk_widget_show (button_retour_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed34), button_retour_ajouter, 56, 504);
  gtk_widget_set_size_request (button_retour_ajouter, 136, 40);

  alignment64 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment64);
  gtk_container_add (GTK_CONTAINER (button_retour_ajouter), alignment64);

  hbox63 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox63);
  gtk_container_add (GTK_CONTAINER (alignment64), hbox63);

  image62 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image62);
  gtk_box_pack_start (GTK_BOX (hbox63), image62, FALSE, FALSE, 0);

  label292 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Retour</b></span>"));
  gtk_widget_show (label292);
  gtk_box_pack_start (GTK_BOX (hbox63), label292, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label292), TRUE);

  button_ok_ajouter_obs = gtk_button_new ();
  gtk_widget_show (button_ok_ajouter_obs);
  gtk_fixed_put (GTK_FIXED (fixed34), button_ok_ajouter_obs, 272, 504);
  gtk_widget_set_size_request (button_ok_ajouter_obs, 136, 40);

  alignment63 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment63);
  gtk_container_add (GTK_CONTAINER (button_ok_ajouter_obs), alignment63);

  hbox62 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox62);
  gtk_container_add (GTK_CONTAINER (alignment63), hbox62);

  image61 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image61);
  gtk_box_pack_start (GTK_BOX (hbox62), image61, FALSE, FALSE, 0);

  label289 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>Confirmer</b></span>"));
  gtk_widget_show (label289);
  gtk_box_pack_start (GTK_BOX (hbox62), label289, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label289), TRUE);

  checkbuttonOrganisationmondial = gtk_check_button_new_with_mnemonic (_("Organisation mondial"));
  gtk_widget_show (checkbuttonOrganisationmondial);
  gtk_fixed_put (GTK_FIXED (fixed34), checkbuttonOrganisationmondial, 192, 360);
  gtk_widget_set_size_request (checkbuttonOrganisationmondial, 192, 32);

  label284 = gtk_label_new (_("<span foreground=\"black\"><b>ID </b></span>"));
  gtk_widget_show (label284);
  gtk_fixed_put (GTK_FIXED (fixed34), label284, 40, 40);
  gtk_widget_set_size_request (label284, 120, 24);
  gtk_label_set_use_markup (GTK_LABEL (label284), TRUE);

  label334 = gtk_label_new (_("<span foreground=\"black\"><b>Prenom </b></span>"));
  gtk_widget_show (label334);
  gtk_fixed_put (GTK_FIXED (fixed34), label334, 80, 72);
  gtk_widget_set_size_request (label334, 56, 24);
  gtk_label_set_use_markup (GTK_LABEL (label334), TRUE);

  label283 = gtk_label_new (_("<span foreground=\"black\"><b>Nom </b></span>"));
  gtk_widget_show (label283);
  gtk_fixed_put (GTK_FIXED (fixed34), label283, 80, 112);
  gtk_widget_set_size_request (label283, 48, 24);
  gtk_label_set_use_markup (GTK_LABEL (label283), TRUE);

  label281 = gtk_label_new (_("<span foreground=\"black\"><b>Date de naissance</b></span>"));
  gtk_widget_show (label281);
  gtk_fixed_put (GTK_FIXED (fixed34), label281, 16, 144);
  gtk_widget_set_size_request (label281, 136, 32);
  gtk_label_set_use_markup (GTK_LABEL (label281), TRUE);

  label277 = gtk_label_new (_("<span foreground=\"black\"><b>Genre</b></span>"));
  gtk_widget_show (label277);
  gtk_fixed_put (GTK_FIXED (fixed34), label277, 72, 184);
  gtk_widget_set_size_request (label277, 56, 24);
  gtk_label_set_use_markup (GTK_LABEL (label277), TRUE);

  label278 = gtk_label_new (_("<span foreground=\"black\"><b>Nationalit\303\251</b></span>"));
  gtk_widget_show (label278);
  gtk_fixed_put (GTK_FIXED (fixed34), label278, 48, 216);
  gtk_widget_set_size_request (label278, 88, 40);
  gtk_label_set_use_markup (GTK_LABEL (label278), TRUE);

  label279 = gtk_label_new (_("<span foreground=\"black\"><b>CIL/Passeport</b></span>"));
  gtk_widget_show (label279);
  gtk_fixed_put (GTK_FIXED (fixed34), label279, 32, 264);
  gtk_widget_set_size_request (label279, 120, 24);
  gtk_label_set_use_markup (GTK_LABEL (label279), TRUE);

  label274 = gtk_label_new (_("<span foreground=\"black\"><b>Appartenance</b></span>"));
  gtk_widget_show (label274);
  gtk_fixed_put (GTK_FIXED (fixed34), label274, 32, 336);
  gtk_widget_set_size_request (label274, 104, 24);
  gtk_label_set_use_markup (GTK_LABEL (label274), TRUE);

  label280 = gtk_label_new (_("<span foreground=\"red\"><b>Ajouter un observateur</b></span>"));
  gtk_widget_show (label280);
  gtk_fixed_put (GTK_FIXED (fixed34), label280, 208, 8);
  gtk_widget_set_size_request (label280, 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label280), TRUE);

  g_signal_connect ((gpointer) checkbutton1_ajt_obs, "toggled",
                    G_CALLBACK (on_checkbutton1_ajt_obs_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton4_ajt_obs, "toggled",
                    G_CALLBACK (on_checkbutton4_ajt_obs_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3_ajt_obs, "toggled",
                    G_CALLBACK (on_checkbutton3_ajt_obs_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton5_ajt_obs, "toggled",
                    G_CALLBACK (on_checkbutton5_ajt_obs_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton44, "toggled",
                    G_CALLBACK (on_radiobutton44_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton43, "toggled",
                    G_CALLBACK (on_radiobutton43_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_retour_ajouter, "clicked",
                    G_CALLBACK (on_button_retour_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ok_ajouter_obs, "clicked",
                    G_CALLBACK (on_button_ok_ajouter_obs_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonOrganisationmondial, "toggled",
                    G_CALLBACK (on_checkbuttonOrganisationmondial_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter_observateur, Ajouter_observateur, "Ajouter_observateur");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, fixed40, "fixed40");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, fixed34, "fixed34");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, entry_pass, "entry_pass");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, fixed35, "fixed35");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, entry_nom_obs, "entry_nom_obs");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, entry_prenom_obs, "entry_prenom_obs");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, spinbutton38, "spinbutton38");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, spinbutton39, "spinbutton39");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, spinbutton40, "spinbutton40");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, entry_id_obs, "entry_id_obs");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, comboboxentry19, "comboboxentry19");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, checkbutton1_ajt_obs, "checkbutton1_ajt_obs");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, checkbutton4_ajt_obs, "checkbutton4_ajt_obs");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, checkbutton3_ajt_obs, "checkbutton3_ajt_obs");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, checkbutton5_ajt_obs, "checkbutton5_ajt_obs");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, radiobutton44, "radiobutton44");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, radiobutton43, "radiobutton43");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, button_retour_ajouter, "button_retour_ajouter");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, alignment64, "alignment64");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, hbox63, "hbox63");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, image62, "image62");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, label292, "label292");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, button_ok_ajouter_obs, "button_ok_ajouter_obs");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, alignment63, "alignment63");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, hbox62, "hbox62");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, image61, "image61");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, label289, "label289");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, checkbuttonOrganisationmondial, "checkbuttonOrganisationmondial");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, label284, "label284");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, label334, "label334");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, label283, "label283");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, label281, "label281");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, label277, "label277");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, label278, "label278");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, label279, "label279");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, label274, "label274");
  GLADE_HOOKUP_OBJECT (Ajouter_observateur, label280, "label280");

  return Ajouter_observateur;
}

GtkWidget*
create_Modifier_Observateur (void)
{
  GtkWidget *Modifier_Observateur;
  GtkWidget *fixed41;
  GtkWidget *fixed37;
  GtkWidget *entrypass_mdf;
  GtkWidget *fixed38;
  GtkWidget *entrynom_mdf;
  GtkWidget *entryprenom_mdf;
  GtkObject *spinbutton45_mdf_adj;
  GtkWidget *spinbutton45_mdf;
  GtkObject *spinbutton46_mdf_adj;
  GtkWidget *spinbutton46_mdf;
  GtkObject *spinbutton47_mdf_adj;
  GtkWidget *spinbutton47_mdf;
  GtkWidget *buttonretour_modif_ob;
  GtkWidget *alignment66;
  GtkWidget *hbox65;
  GtkWidget *image64;
  GtkWidget *label313;
  GtkWidget *button_ok1_modif_obs;
  GtkWidget *alignment67;
  GtkWidget *hbox66;
  GtkWidget *image65;
  GtkWidget *label314;
  GtkWidget *radiobutton45_mdf;
  GSList *radiobutton45_mdf_group = NULL;
  GtkWidget *radiobutton46_mdf;
  GtkWidget *checkbutton52_mdf;
  GtkWidget *checkbutton51_mdf;
  GtkWidget *checkbutton50_mdf;
  GtkWidget *checkbutton48_mdf;
  GtkWidget *comboboxentry20_mdf;
  GtkWidget *entryid_mdf;
  GtkWidget *label316;
  GtkWidget *label317;
  GtkWidget *label318;
  GtkWidget *label319;
  GtkWidget *label320;
  GtkWidget *label321;
  GtkWidget *label322;
  GtkWidget *label328;
  GtkWidget *label315;
  GtkWidget *checkbutton2Organisationmondial_mdf;

  Modifier_Observateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Modifier_Observateur, 480, 600);
  gtk_window_set_title (GTK_WINDOW (Modifier_Observateur), _("Modifier Observateur"));

  fixed41 = gtk_fixed_new ();
  gtk_widget_show (fixed41);
  gtk_container_add (GTK_CONTAINER (Modifier_Observateur), fixed41);
  gtk_widget_set_size_request (fixed41, 480, 600);

  fixed37 = gtk_fixed_new ();
  gtk_widget_show (fixed37);
  gtk_fixed_put (GTK_FIXED (fixed41), fixed37, 0, 0);
  gtk_widget_set_size_request (fixed37, 0, 0);

  entrypass_mdf = gtk_entry_new ();
  gtk_widget_show (entrypass_mdf);
  gtk_fixed_put (GTK_FIXED (fixed37), entrypass_mdf, 200, 264);
  gtk_widget_set_size_request (entrypass_mdf, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrypass_mdf), 8226);

  fixed38 = gtk_fixed_new ();
  gtk_widget_show (fixed38);
  gtk_fixed_put (GTK_FIXED (fixed37), fixed38, 160, 136);
  gtk_widget_set_size_request (fixed38, 50, 50);

  entrynom_mdf = gtk_entry_new ();
  gtk_widget_show (entrynom_mdf);
  gtk_fixed_put (GTK_FIXED (fixed37), entrynom_mdf, 200, 112);
  gtk_widget_set_size_request (entrynom_mdf, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom_mdf), 8226);

  entryprenom_mdf = gtk_entry_new ();
  gtk_widget_show (entryprenom_mdf);
  gtk_fixed_put (GTK_FIXED (fixed37), entryprenom_mdf, 200, 72);
  gtk_widget_set_size_request (entryprenom_mdf, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenom_mdf), 8226);

  spinbutton45_mdf_adj = gtk_adjustment_new (23, 1, 31, 1, 10, 10);
  spinbutton45_mdf = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton45_mdf_adj), 1, 0);
  gtk_widget_show (spinbutton45_mdf);
  gtk_fixed_put (GTK_FIXED (fixed37), spinbutton45_mdf, 192, 144);
  gtk_widget_set_size_request (spinbutton45_mdf, 60, 27);

  spinbutton46_mdf_adj = gtk_adjustment_new (12, 1, 12, 1, 10, 10);
  spinbutton46_mdf = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton46_mdf_adj), 1, 0);
  gtk_widget_show (spinbutton46_mdf);
  gtk_fixed_put (GTK_FIXED (fixed37), spinbutton46_mdf, 256, 144);
  gtk_widget_set_size_request (spinbutton46_mdf, 60, 27);

  spinbutton47_mdf_adj = gtk_adjustment_new (2000, 1899, 2005, 1, 10, 10);
  spinbutton47_mdf = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton47_mdf_adj), 1, 0);
  gtk_widget_show (spinbutton47_mdf);
  gtk_fixed_put (GTK_FIXED (fixed37), spinbutton47_mdf, 320, 144);
  gtk_widget_set_size_request (spinbutton47_mdf, 60, 27);

  buttonretour_modif_ob = gtk_button_new ();
  gtk_widget_show (buttonretour_modif_ob);
  gtk_fixed_put (GTK_FIXED (fixed37), buttonretour_modif_ob, 32, 552);
  gtk_widget_set_size_request (buttonretour_modif_ob, 136, 40);

  alignment66 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment66);
  gtk_container_add (GTK_CONTAINER (buttonretour_modif_ob), alignment66);

  hbox65 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox65);
  gtk_container_add (GTK_CONTAINER (alignment66), hbox65);

  image64 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image64);
  gtk_box_pack_start (GTK_BOX (hbox65), image64, FALSE, FALSE, 0);

  label313 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Retour</b></span>"));
  gtk_widget_show (label313);
  gtk_box_pack_start (GTK_BOX (hbox65), label313, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label313), TRUE);

  button_ok1_modif_obs = gtk_button_new ();
  gtk_widget_show (button_ok1_modif_obs);
  gtk_fixed_put (GTK_FIXED (fixed37), button_ok1_modif_obs, 256, 552);
  gtk_widget_set_size_request (button_ok1_modif_obs, 152, 40);

  alignment67 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment67);
  gtk_container_add (GTK_CONTAINER (button_ok1_modif_obs), alignment67);

  hbox66 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox66);
  gtk_container_add (GTK_CONTAINER (alignment67), hbox66);

  image65 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image65);
  gtk_box_pack_start (GTK_BOX (hbox66), image65, FALSE, FALSE, 0);

  label314 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>Confirmer</b></span>"));
  gtk_widget_show (label314);
  gtk_box_pack_start (GTK_BOX (hbox66), label314, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label314), TRUE);

  radiobutton45_mdf = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton45_mdf);
  gtk_fixed_put (GTK_FIXED (fixed37), radiobutton45_mdf, 192, 184);
  gtk_widget_set_size_request (radiobutton45_mdf, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton45_mdf), radiobutton45_mdf_group);
  radiobutton45_mdf_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton45_mdf));

  radiobutton46_mdf = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton46_mdf);
  gtk_fixed_put (GTK_FIXED (fixed37), radiobutton46_mdf, 312, 184);
  gtk_widget_set_size_request (radiobutton46_mdf, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton46_mdf), radiobutton45_mdf_group);
  radiobutton45_mdf_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton46_mdf));

  checkbutton52_mdf = gtk_check_button_new_with_mnemonic (_("Societ\303\251 civile"));
  gtk_widget_show (checkbutton52_mdf);
  gtk_fixed_put (GTK_FIXED (fixed37), checkbutton52_mdf, 184, 480);
  gtk_widget_set_size_request (checkbutton52_mdf, 168, 24);

  checkbutton51_mdf = gtk_check_button_new_with_mnemonic (_("Presse"));
  gtk_widget_show (checkbutton51_mdf);
  gtk_fixed_put (GTK_FIXED (fixed37), checkbutton51_mdf, 184, 440);
  gtk_widget_set_size_request (checkbutton51_mdf, 128, 32);

  checkbutton50_mdf = gtk_check_button_new_with_mnemonic (_("Hote"));
  gtk_widget_show (checkbutton50_mdf);
  gtk_fixed_put (GTK_FIXED (fixed37), checkbutton50_mdf, 184, 408);
  gtk_widget_set_size_request (checkbutton50_mdf, 160, 24);

  checkbutton48_mdf = gtk_check_button_new_with_mnemonic (_("Parti politique"));
  gtk_widget_show (checkbutton48_mdf);
  gtk_fixed_put (GTK_FIXED (fixed37), checkbutton48_mdf, 184, 328);
  gtk_widget_set_size_request (checkbutton48_mdf, 176, 32);

  comboboxentry20_mdf = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry20_mdf);
  gtk_fixed_put (GTK_FIXED (fixed37), comboboxentry20_mdf, 192, 224);
  gtk_widget_set_size_request (comboboxentry20_mdf, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry20_mdf), _("Nationale"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry20_mdf), _("Internationale"));

  entryid_mdf = gtk_label_new ("");
  gtk_widget_show (entryid_mdf);
  gtk_fixed_put (GTK_FIXED (fixed37), entryid_mdf, 200, 32);
  gtk_widget_set_size_request (entryid_mdf, 152, 32);

  label316 = gtk_label_new (_("<span foreground=\"black\"><b>ID </b></span>"));
  gtk_widget_show (label316);
  gtk_fixed_put (GTK_FIXED (fixed37), label316, 40, 40);
  gtk_widget_set_size_request (label316, 120, 24);
  gtk_label_set_use_markup (GTK_LABEL (label316), TRUE);

  label317 = gtk_label_new (_("<span foreground=\"black\"><b>Pr\303\251nom</b></span>"));
  gtk_widget_show (label317);
  gtk_fixed_put (GTK_FIXED (fixed37), label317, 80, 72);
  gtk_widget_set_size_request (label317, 56, 24);
  gtk_label_set_use_markup (GTK_LABEL (label317), TRUE);

  label318 = gtk_label_new (_("<span foreground=\"black\"><b>Nom</b></span>"));
  gtk_widget_show (label318);
  gtk_fixed_put (GTK_FIXED (fixed37), label318, 80, 112);
  gtk_widget_set_size_request (label318, 48, 24);
  gtk_label_set_use_markup (GTK_LABEL (label318), TRUE);

  label319 = gtk_label_new (_("<span foreground=\"black\"><b>Date de naissance</b></span>"));
  gtk_widget_show (label319);
  gtk_fixed_put (GTK_FIXED (fixed37), label319, 16, 144);
  gtk_widget_set_size_request (label319, 136, 32);
  gtk_label_set_use_markup (GTK_LABEL (label319), TRUE);

  label320 = gtk_label_new (_("<span foreground=\"black\"><b>Genre</b></span>"));
  gtk_widget_show (label320);
  gtk_fixed_put (GTK_FIXED (fixed37), label320, 72, 184);
  gtk_widget_set_size_request (label320, 56, 24);
  gtk_label_set_use_markup (GTK_LABEL (label320), TRUE);

  label321 = gtk_label_new (_("<span foreground=\"black\"><b>Nationalit\303\251</b></span>"));
  gtk_widget_show (label321);
  gtk_fixed_put (GTK_FIXED (fixed37), label321, 48, 216);
  gtk_widget_set_size_request (label321, 88, 40);
  gtk_label_set_use_markup (GTK_LABEL (label321), TRUE);

  label322 = gtk_label_new (_("<span foreground=\"black\"><b>CIL/Passeport</b></span>"));
  gtk_widget_show (label322);
  gtk_fixed_put (GTK_FIXED (fixed37), label322, 32, 264);
  gtk_widget_set_size_request (label322, 120, 24);
  gtk_label_set_use_markup (GTK_LABEL (label322), TRUE);

  label328 = gtk_label_new (_("<span foreground=\"black\"><b>Appartenance</b></span>"));
  gtk_widget_show (label328);
  gtk_fixed_put (GTK_FIXED (fixed37), label328, 32, 336);
  gtk_widget_set_size_request (label328, 104, 24);
  gtk_label_set_use_markup (GTK_LABEL (label328), TRUE);

  label315 = gtk_label_new (_("<span foreground=\"red\"><b>Modifier un observateur</b></span>"));
  gtk_widget_show (label315);
  gtk_fixed_put (GTK_FIXED (fixed37), label315, 208, 8);
  gtk_widget_set_size_request (label315, 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label315), TRUE);

  checkbutton2Organisationmondial_mdf = gtk_check_button_new_with_mnemonic (_("Organisation mondial"));
  gtk_widget_show (checkbutton2Organisationmondial_mdf);
  gtk_fixed_put (GTK_FIXED (fixed37), checkbutton2Organisationmondial_mdf, 184, 368);
  gtk_widget_set_size_request (checkbutton2Organisationmondial_mdf, 200, 24);

  g_signal_connect ((gpointer) buttonretour_modif_ob, "clicked",
                    G_CALLBACK (on_buttonretour_modif_ob_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ok1_modif_obs, "clicked",
                    G_CALLBACK (on_button_ok1_modif_obs_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton45_mdf, "toggled",
                    G_CALLBACK (on_radiobutton45_mdf_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton46_mdf, "toggled",
                    G_CALLBACK (on_radiobutton46_mdf_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton52_mdf, "toggled",
                    G_CALLBACK (on_checkbutton52_mdf_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton51_mdf, "toggled",
                    G_CALLBACK (on_checkbutton51_mdf_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton50_mdf, "toggled",
                    G_CALLBACK (on_checkbutton50_mdf_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton48_mdf, "toggled",
                    G_CALLBACK (on_checkbutton48_mdf_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2Organisationmondial_mdf, "toggled",
                    G_CALLBACK (on_checkbutton2Organisationmondial_mdf_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifier_Observateur, Modifier_Observateur, "Modifier_Observateur");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, fixed41, "fixed41");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, fixed37, "fixed37");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, entrypass_mdf, "entrypass_mdf");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, fixed38, "fixed38");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, entrynom_mdf, "entrynom_mdf");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, entryprenom_mdf, "entryprenom_mdf");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, spinbutton45_mdf, "spinbutton45_mdf");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, spinbutton46_mdf, "spinbutton46_mdf");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, spinbutton47_mdf, "spinbutton47_mdf");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, buttonretour_modif_ob, "buttonretour_modif_ob");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, alignment66, "alignment66");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, hbox65, "hbox65");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, image64, "image64");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, label313, "label313");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, button_ok1_modif_obs, "button_ok1_modif_obs");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, alignment67, "alignment67");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, hbox66, "hbox66");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, image65, "image65");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, label314, "label314");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, radiobutton45_mdf, "radiobutton45_mdf");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, radiobutton46_mdf, "radiobutton46_mdf");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, checkbutton52_mdf, "checkbutton52_mdf");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, checkbutton51_mdf, "checkbutton51_mdf");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, checkbutton50_mdf, "checkbutton50_mdf");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, checkbutton48_mdf, "checkbutton48_mdf");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, comboboxentry20_mdf, "comboboxentry20_mdf");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, entryid_mdf, "entryid_mdf");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, label316, "label316");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, label317, "label317");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, label318, "label318");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, label319, "label319");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, label320, "label320");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, label321, "label321");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, label322, "label322");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, label328, "label328");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, label315, "label315");
  GLADE_HOOKUP_OBJECT (Modifier_Observateur, checkbutton2Organisationmondial_mdf, "checkbutton2Organisationmondial_mdf");

  return Modifier_Observateur;
}

GtkWidget*
create_Supprimer_Observateur (void)
{
  GtkWidget *Supprimer_Observateur;
  GtkWidget *fixed42;
  GtkWidget *fixed32;
  GtkWidget *button_non_sup_obs;
  GtkWidget *alignment60;
  GtkWidget *hbox59;
  GtkWidget *image58;
  GtkWidget *label251;
  GtkWidget *button_oui_supp_obs;
  GtkWidget *alignment61;
  GtkWidget *hbox60;
  GtkWidget *image59;
  GtkWidget *label252;
  GtkWidget *label253;

  Supprimer_Observateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Supprimer_Observateur, 430, 290);
  gtk_window_set_title (GTK_WINDOW (Supprimer_Observateur), _("Supprimer Observateur"));

  fixed42 = gtk_fixed_new ();
  gtk_widget_show (fixed42);
  gtk_container_add (GTK_CONTAINER (Supprimer_Observateur), fixed42);
  gtk_widget_set_size_request (fixed42, 430, 290);

  fixed32 = gtk_fixed_new ();
  gtk_widget_show (fixed32);
  gtk_fixed_put (GTK_FIXED (fixed42), fixed32, 0, 0);
  gtk_widget_set_size_request (fixed32, 0, 0);

  button_non_sup_obs = gtk_button_new ();
  gtk_widget_show (button_non_sup_obs);
  gtk_fixed_put (GTK_FIXED (fixed32), button_non_sup_obs, 304, 248);
  gtk_widget_set_size_request (button_non_sup_obs, 96, 40);

  alignment60 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment60);
  gtk_container_add (GTK_CONTAINER (button_non_sup_obs), alignment60);

  hbox59 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox59);
  gtk_container_add (GTK_CONTAINER (alignment60), hbox59);

  image58 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image58);
  gtk_box_pack_start (GTK_BOX (hbox59), image58, FALSE, FALSE, 0);

  label251 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>NON </b></span>? "));
  gtk_widget_show (label251);
  gtk_box_pack_start (GTK_BOX (hbox59), label251, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label251), TRUE);

  button_oui_supp_obs = gtk_button_new ();
  gtk_widget_show (button_oui_supp_obs);
  gtk_fixed_put (GTK_FIXED (fixed32), button_oui_supp_obs, 128, 248);
  gtk_widget_set_size_request (button_oui_supp_obs, 88, 40);

  alignment61 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment61);
  gtk_container_add (GTK_CONTAINER (button_oui_supp_obs), alignment61);

  hbox60 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox60);
  gtk_container_add (GTK_CONTAINER (alignment61), hbox60);

  image59 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image59);
  gtk_box_pack_start (GTK_BOX (hbox60), image59, FALSE, FALSE, 0);

  label252 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>OUI </b></span>? "));
  gtk_widget_show (label252);
  gtk_box_pack_start (GTK_BOX (hbox60), label252, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label252), TRUE);

  label253 = gtk_label_new (_("<span foreground=\"black\"><b>Voulez vous supprimer l'observateur </b></span>? "));
  gtk_widget_show (label253);
  gtk_fixed_put (GTK_FIXED (fixed32), label253, 96, 80);
  gtk_widget_set_size_request (label253, 336, 120);
  gtk_label_set_use_markup (GTK_LABEL (label253), TRUE);

  g_signal_connect ((gpointer) button_non_sup_obs, "clicked",
                    G_CALLBACK (on_button_non_sup_obs_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_oui_supp_obs, "clicked",
                    G_CALLBACK (on_button_oui_supp_obs_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Supprimer_Observateur, Supprimer_Observateur, "Supprimer_Observateur");
  GLADE_HOOKUP_OBJECT (Supprimer_Observateur, fixed42, "fixed42");
  GLADE_HOOKUP_OBJECT (Supprimer_Observateur, fixed32, "fixed32");
  GLADE_HOOKUP_OBJECT (Supprimer_Observateur, button_non_sup_obs, "button_non_sup_obs");
  GLADE_HOOKUP_OBJECT (Supprimer_Observateur, alignment60, "alignment60");
  GLADE_HOOKUP_OBJECT (Supprimer_Observateur, hbox59, "hbox59");
  GLADE_HOOKUP_OBJECT (Supprimer_Observateur, image58, "image58");
  GLADE_HOOKUP_OBJECT (Supprimer_Observateur, label251, "label251");
  GLADE_HOOKUP_OBJECT (Supprimer_Observateur, button_oui_supp_obs, "button_oui_supp_obs");
  GLADE_HOOKUP_OBJECT (Supprimer_Observateur, alignment61, "alignment61");
  GLADE_HOOKUP_OBJECT (Supprimer_Observateur, hbox60, "hbox60");
  GLADE_HOOKUP_OBJECT (Supprimer_Observateur, image59, "image59");
  GLADE_HOOKUP_OBJECT (Supprimer_Observateur, label252, "label252");
  GLADE_HOOKUP_OBJECT (Supprimer_Observateur, label253, "label253");

  return Supprimer_Observateur;
}

