/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Gestion_observateur (void);
GtkWidget* create_Ajouter_observateur (void);
GtkWidget* create_Modifier_Observateur (void);
GtkWidget* create_Supprimer_Observateur (void);
