/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *dhashbord;
  GtkWidget *gestion_yassine;
  GtkWidget *ajout_yassine;
  GtkWidget *modifier_yassine;
  GtkWidget *supprimer_yassine;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  dhashbord = create_dhashbord ();
  gtk_widget_show (dhashbord);
  /*gestion_yassine = create_gestion_yassine ();
  gtk_widget_show (gestion_yassine);
  ajout_yassine = create_ajout_yassine ();
  gtk_widget_show (ajout_yassine);
  modifier_yassine = create_modifier_yassine ();
  gtk_widget_show (modifier_yassine);
  supprimer_yassine = create_supprimer_yassine ();
  gtk_widget_show (supprimer_yassine);*/

  gtk_main ();
  return 0;
}

