/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Gestion_observateur;
  GtkWidget *Ajouter_observateur;
  GtkWidget *Modifier_Observateur;
  GtkWidget *Supprimer_Observateur;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Gestion_observateur = create_Gestion_observateur ();
  gtk_widget_show (Gestion_observateur);
 /* Ajouter_observateur = create_Ajouter_observateur ();
  gtk_widget_show (Ajouter_observateur);
  Modifier_Observateur = create_Modifier_Observateur ();
  gtk_widget_show (Modifier_Observateur);
  Supprimer_Observateur = create_Supprimer_Observateur ();
  gtk_widget_show (Supprimer_Observateur);*/

  gtk_main ();
  return 0;
}

